# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""my_cli - my_cli package."""

from my_cli.constants import __version__

__all__ = ["__version__"]
