# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""Main CLI entry point."""

import traceback
from typing import Any

import click

from my_cli.commands.config import config
from my_cli.commands.private import private
from my_cli.commands.public import public
from my_cli.constants import (
    SPLASH_COLOR,
    SPLASH_ENABLED,
    SPLASH_FILE,
    __version__,
)
from my_cli.errors import UnexpectedError, reported
from my_cli.log import hex_to_rgb, log_debug
from my_cli.options import common_options


def _show_splash() -> None:
    """Display splash screen if enabled."""
    if SPLASH_ENABLED and SPLASH_FILE and SPLASH_FILE.exists():
        splash_text = SPLASH_FILE.read_text()
        if SPLASH_COLOR:
            rgb = hex_to_rgb(SPLASH_COLOR)
            click.secho(splash_text, fg=rgb)
        else:
            click.echo(splash_text)


class RootGroup(click.Group):
    """The root group, reporting what Click raises on its own as JSON too.

    Click's main() shows a ClickException and exits with its code; wrapping the
    parsing and the dispatch turns everything else into one of the CLI's errors
    first, so every failure is the one JSON document on stdout.
    """

    def make_context(
        self,
        info_name: str | None,
        args: list[str],
        parent: click.Context | None = None,
        **extra: Any,
    ) -> click.Context:
        with reported():
            return super().make_context(info_name, args, parent, **extra)

    def invoke(self, ctx: click.Context) -> Any:
        try:
            with reported():
                return super().invoke(ctx)
        except UnexpectedError as e:
            # The traceback the bug came with, kept for --debug
            log_debug("".join(traceback.format_exception(e.__cause__)))
            raise


@click.group(
    cls=RootGroup,
    invoke_without_command=True,
    help="A CLI application",
)
@click.version_option(version=__version__)
@common_options
@click.pass_context
def main(ctx: click.Context) -> None:
    """Main CLI entry point."""
    # Skipped while Click is parsing for shell completion
    if not ctx.resilient_parsing:
        _show_splash()

    # Show help when no subcommand is invoked
    if ctx.invoked_subcommand is None:
        click.echo(ctx.get_help())


main.add_command(config)
main.add_command(private)
main.add_command(public)


if __name__ == "__main__":
    main()
