# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""HTTP client for API requests."""

from pathlib import Path
from typing import Any
from urllib.parse import quote

import requests

from my_cli.constants import DEFAULT_BASE_URL, DEFAULT_CA_FILE, DEFAULT_TIMEOUT
from my_cli.logging import log_debug
from my_cli.redaction import redact, redact_text


def encode_path_param(value: Any) -> str:
    """Encode a value for interpolation into a single URL path segment.

    Nothing is left safe, so a value containing "/", "?" or "#" becomes one
    segment instead of changing which resource the request addresses.
    """
    return quote(str(value), safe="")


class ApiClient:
    """HTTP client for making API requests."""

    def __init__(
        self,
        base_url: str | None = None,
        access_token: str | None = None,
        timeout: int = DEFAULT_TIMEOUT,
        ca_file: str | None = DEFAULT_CA_FILE,
        verify_ssl: bool = True,
        debug: bool = False,
    ) -> None:
        """Initialize the API client."""
        self.base_url = (base_url or DEFAULT_BASE_URL).rstrip("/")
        self.access_token = access_token
        self.timeout = timeout
        self.ca_file = ca_file
        self.verify_ssl = verify_ssl
        self.debug = debug
        self.session = requests.Session()
        self._setup_headers()
        self._setup_ssl()

    def _setup_headers(self) -> None:
        """Set up default headers."""
        self.session.headers["Content-Type"] = "application/json"
        self.session.headers["Accept"] = "application/json"
        if self.access_token:
            auth_header = f"Bearer {self.access_token}"
            self.session.headers["Authorization"] = auth_header

    def _setup_ssl(self) -> None:
        """Set up SSL verification with custom CA file if provided."""
        if not self.verify_ssl:
            self.session.verify = False
        elif self.ca_file:
            ca_path = Path(self.ca_file)
            if isinstance(self.ca_file, str) and ca_path.exists():
                self.session.verify = str(ca_path)

    def _url(self, path: str) -> str:
        """Build full URL from path."""
        return f"{self.base_url}{path}"

    def _log_request(
        self,
        method: str,
        url: str,
        params: dict | None = None,
        json_data: dict | None = None,
    ) -> None:
        """Log request details when debug is enabled."""
        if not self.debug:
            return
        log_debug(f"Request: {method} {url}")
        if params:
            log_debug(f"Params: {redact(params)}")
        if json_data:
            log_debug(f"Body: {redact(json_data)}")
        log_debug(f"Headers: {redact(self.session.headers)}")

    def _log_response(self, response: requests.Response) -> None:
        """Log response details when debug is enabled."""
        if not self.debug:
            return
        log_debug(f"Response: {response.status_code} {response.reason}")
        log_debug(f"Response Headers: {redact(response.headers)}")
        if response.text:
            # Redact before truncating: cutting the body first would leave a
            # partial credential that no longer matches any pattern.
            log_debug(f"Response Body: {redact_text(response.text)[:1000]}")

    def get(
        self,
        path: str,
        params: dict[str, Any] | None = None,
    ) -> requests.Response:
        """Make a GET request."""
        url = self._url(path)
        self._log_request("GET", url, params=params)
        response = self.session.get(url, params=params, timeout=self.timeout)
        self._log_response(response)
        return response

    def post(
        self,
        path: str,
        json_data: dict[str, Any] | None = None,
        params: dict[str, Any] | None = None,
    ) -> requests.Response:
        """Make a POST request."""
        url = self._url(path)
        self._log_request("POST", url, params=params, json_data=json_data)
        response = self.session.post(
            url, json=json_data, params=params, timeout=self.timeout
        )
        self._log_response(response)
        return response

    def put(
        self,
        path: str,
        json_data: dict[str, Any] | None = None,
        params: dict[str, Any] | None = None,
    ) -> requests.Response:
        """Make a PUT request."""
        url = self._url(path)
        self._log_request("PUT", url, params=params, json_data=json_data)
        response = self.session.put(
            url, json=json_data, params=params, timeout=self.timeout
        )
        self._log_response(response)
        return response

    def patch(
        self,
        path: str,
        json_data: dict[str, Any] | None = None,
        params: dict[str, Any] | None = None,
    ) -> requests.Response:
        """Make a PATCH request."""
        url = self._url(path)
        self._log_request("PATCH", url, params=params, json_data=json_data)
        response = self.session.patch(
            url, json=json_data, params=params, timeout=self.timeout
        )
        self._log_response(response)
        return response

    def delete(
        self,
        path: str,
        json_data: dict[str, Any] | None = None,
        params: dict[str, Any] | None = None,
    ) -> requests.Response:
        """Make a DELETE request."""
        url = self._url(path)
        self._log_request("DELETE", url, params=params, json_data=json_data)
        response = self.session.delete(
            url, json=json_data, params=params, timeout=self.timeout
        )
        self._log_response(response)
        return response
