# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""Constants for the generated CLI."""

import os
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

try:
    __version__ = version("my_cli")
except PackageNotFoundError:
    __version__ = "0.0.0"

# Main directory for CLI data (config, cache, etc.)
MAIN_DIR = Path(os.path.expandvars("${HOME}/.my-cli"))

# Profile configuration
PROFILE_FILE = Path(os.path.expandvars("${HOME}/.my-cli/profiles.yaml"))

DEFAULT_BASE_URL = "http://localhost:3000"
DEFAULT_TIMEOUT = 30
DEFAULT_CA_FILE = None

# Splash screen configuration
SPLASH_ENABLED = False
SPLASH_FILE = None
SPLASH_COLOR = None

# Profile defaults (generated from cli-wizard configuration)
PROFILE_DEFAULTS: dict[str, object] = {
    "baseUrl": "http://localhost:3000",
    "timeout": 30,
    "outputFormat": "json",
    "outputColors": True,
    "jsonIndent": 2,
    "tableStyle": "rounded",
    "logLevel": "INFO",
    "retryMaxAttempts": 3,
    "retryBackoffFactor": 0.5,
    "accessToken": None,
}

# Log configuration
LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s [%(levelname)s] %(message)s"
LOG_TIMESTAMP_FORMAT = "%Y-%m-%dT%H:%M:%S"
LOG_TIMEZONE = "UTC"
LOG_FILE = None
LOG_ROTATION_TYPE = "days"
LOG_ROTATION_SIZE_MB = 10
LOG_ROTATION_DAYS = 30
LOG_ROTATION_BACKUP_COUNT = 5

# Log color configuration
LOG_COLOR_STYLE = "level"
LOG_COLORS = {
    "DEBUG": "#808080",
    "INFO": "#00FF00",
    "WARNING": "#FFFF00",
    "ERROR": "#FF0000",
}
