# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""The errors a command exits with, one class per failure, and their exit codes.

Every failure the CLI reports is one of these classes, so a caller can catch
them by class and a script can branch on the exit code. They are Click
exceptions, so Click shows them and exits with their code; nothing raises a
Click class directly. This module sits below the options, which raise one of
these, so it reads the invocation state itself rather than through the log.
"""

from typing import IO, Any

import click

from my_cli.constants import PROFILE_DEFAULTS

# Exit codes of a failed command, one per failure class, so a calling script
# can tell them apart and branch or retry accordingly. 2 is Click's own, for
# a usage error, and 1 is what is left: a response that could not be decoded
# or a setting the CLI cannot work with.
EXIT_FAILURE = 1
EXIT_USAGE = 2
EXIT_NETWORK = 3
EXIT_AUTH = 4
EXIT_CLIENT_ERROR = 5
EXIT_SERVER_ERROR = 6


def colors_enabled() -> bool:
    """Check if coloured console output is enabled, as the profile set it."""
    ctx = click.get_current_context(silent=True)
    settings = ctx.ensure_object(dict) if ctx is not None else {}
    return bool(settings.get("colors", PROFILE_DEFAULTS.get("outputColors", True)))


class CliError(click.ClickException):
    """Base of every error the CLI reports, exiting with the code of its class.

    This base one is what is left after the classes below: a response the
    command could not decode above all.
    """

    exit_code = EXIT_FAILURE

    def __init__(self, message: str) -> None:
        super().__init__(message)
        # Decided now, inside the invocation: Click shows the error after the
        # context, and the colour setting the profile put there, is gone.
        self.colored = colors_enabled()

    def show(self, file: IO[Any] | None = None) -> None:
        """Print the error to stderr, in red when colours are on."""
        click.secho(
            f"Error: {self.format_message()}",
            fg="red" if self.colored else None,
            file=file,
            err=True,
        )


class ConfigError(CliError):
    """A setting the CLI cannot work with: the profile file could not be read
    or written, or a configured file does not exist."""


class ResponseError(CliError):
    """A successful response the CLI could not decode."""


class RequestError(CliError):
    """A request that failed; the subclasses say how, and with which code."""


class NetworkError(RequestError):
    """The request got no response: refused, unknown host, timeout, TLS."""

    exit_code = EXIT_NETWORK


class AuthError(RequestError):
    """The API refused the credentials, or their absence: a 401 or 403."""

    exit_code = EXIT_AUTH


class ClientError(RequestError):
    """The API rejected the request: any other 4xx."""

    exit_code = EXIT_CLIENT_ERROR


class ServerError(RequestError):
    """The API failed: a 5xx."""

    exit_code = EXIT_SERVER_ERROR


class InvalidHeaderError(click.BadParameter, CliError):
    """A --header value that is not ``Name: value``.

    A usage error like any bad option: BadParameter comes first, so Click
    prints the usage line, names the option and exits with EXIT_USAGE, while
    the error is still one of the CLI's own.
    """
