# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""The errors a command exits with, one class per failure, and their exit codes.

Every failure the CLI reports is one of these classes, so a caller can catch
them by class and a script can branch on the exit code. They are Click
exceptions, so Click shows them and exits with their code; nothing raises a
Click class directly. Shown, an error is one JSON document on stdout, the only
thing a failed invocation prints there::

    {"error": {"type": "NetworkError", "message": "...", "exitCode": 3}}

This module sits below the options, which raise ClientError for a malformed
--header, so it imports nothing above the invocation state.
"""

import json
from collections.abc import Iterator
from contextlib import contextmanager
from typing import IO, Any

import click

from my_cli.constants import PROFILE_DEFAULTS
from my_cli.state import state

# Exit codes of a failed command, one per error class, so a calling script
# can tell them apart and branch or retry accordingly. 2 is Click's own, for
# a usage error, and 1 is what is left: a Click error that is not about usage.
EXIT_FAILURE = 1
EXIT_USAGE = 2
EXIT_NETWORK = 3
EXIT_CLIENT_ERROR = 4
EXIT_SERVER_ERROR = 5
EXIT_RESPONSE = 6
EXIT_CONFIG = 7
EXIT_UNEXPECTED = 8


class CliError(click.ClickException):
    """Base of every error the CLI reports, exiting with the code of its class.

    This base one is what is left after the classes below.
    """

    exit_code = EXIT_FAILURE

    def __init__(self, message: str) -> None:
        super().__init__(message)
        # Read now, inside the invocation: Click shows the error after the
        # context, and the setting the profile put there, is gone.
        self.json_indent = int(
            state().get("json_indent", PROFILE_DEFAULTS.get("jsonIndent", 2))
        )

    def to_dict(self) -> dict[str, Any]:
        """The document a caller parses: the class, the message and the code."""
        return {
            "error": {
                "type": type(self).__name__,
                "message": self.format_message(),
                "exitCode": self.exit_code,
            }
        }

    def show(self, file: IO[Any] | None = None) -> None:
        """Print the error document to stdout, where the result would have gone."""
        click.echo(json.dumps(self.to_dict(), indent=self.json_indent), file=file)


class ConfigError(CliError):
    """A setting the CLI cannot work with: the profile file could not be read
    or written, or a configured file does not exist."""

    exit_code = EXIT_CONFIG


class ResponseError(CliError):
    """A successful response the CLI could not decode."""

    exit_code = EXIT_RESPONSE


class RequestError(CliError):
    """A request that failed; the subclasses say how, and with which code."""


class NetworkError(RequestError):
    """The request got no response: refused, unknown host, timeout, TLS."""

    exit_code = EXIT_NETWORK


class ClientError(RequestError):
    """The request is wrong: the API rejected it with a 4xx, a refused
    credential included, or a --header the CLI could not send, one that is
    not ``Name: value``."""

    exit_code = EXIT_CLIENT_ERROR


class ServerError(RequestError):
    """The API failed: a 5xx."""

    exit_code = EXIT_SERVER_ERROR


class UsageError(CliError, click.UsageError):
    """A bad invocation: an unknown command, a missing option or a bad value.

    What Click raises itself while parsing, wrapped by ``reported`` so it is
    shown as JSON like every other failure, with Click's exit code for it.
    """

    exit_code = EXIT_USAGE


class UnexpectedError(CliError):
    """An error that is not the CLI's own: a bug, reported with its type."""

    exit_code = EXIT_UNEXPECTED

    def __init__(self, error: BaseException) -> None:
        super().__init__(f"{type(error).__name__}: {error}")


@contextmanager
def reported() -> Iterator[None]:
    """Turn whatever escapes the block into one of the CLI's errors.

    Click's main() shows a ClickException and exits with its code, so wrapping
    the parsing and the dispatch of the root group in this guard makes every
    failure a JSON document on stdout. The CLI's own errors and Click's flow
    control, the exit behind --help and the abort behind Ctrl-C, pass through.
    """
    try:
        yield
    except (CliError, click.exceptions.Exit, click.Abort, EOFError):
        raise
    except click.UsageError as e:
        raise UsageError(e.format_message()) from e
    except click.ClickException as e:
        raise CliError(e.format_message()) from e
    except Exception as e:
        raise UnexpectedError(e) from e
