# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""Logging utilities for the generated CLI."""

from datetime import datetime, timezone
from logging import makeLogRecord
from logging.handlers import (
    BaseRotatingHandler,
    RotatingFileHandler,
    TimedRotatingFileHandler,
)
from typing import Literal

import click

from my_cli.constants import (
    LOG_COLOR_STYLE,
    LOG_COLORS,
    LOG_FILE,
    LOG_FORMAT,
    LOG_LEVEL,
    LOG_ROTATION_BACKUP_COUNT,
    LOG_ROTATION_DAYS,
    LOG_ROTATION_SIZE_MB,
    LOG_ROTATION_TYPE,
    LOG_TIMESTAMP_FORMAT,
    LOG_TIMEZONE,
    PROFILE_DEFAULTS,
)
from my_cli.options import state

# Log level priorities
_LOG_LEVELS = {
    "DEBUG": 10,
    "INFO": 20,
    "WARNING": 30,
    "ERROR": 40,
}


def _debug_enabled() -> bool:
    """Check if --debug was given to the running invocation."""
    return bool(state().get("debug", False))


def _log_level() -> str:
    """Get the level below which messages are dropped.

    The generated default, until a profile is loaded: resolving the setting
    against the profile and the environment lives in the profile module, which
    imports this one, so the resolved value is pushed into the state instead.
    """
    return str(state().get("log_level", LOG_LEVEL))


def colors_enabled() -> bool:
    """Check if coloured console output is enabled."""
    return bool(state().get("colors", PROFILE_DEFAULTS.get("outputColors", True)))


def _should_log(level: str) -> bool:
    """Check if a message at the given level should be logged."""
    if _debug_enabled():
        return True
    level_priority = _LOG_LEVELS.get(level, 20)
    config_priority = _LOG_LEVELS.get(_log_level(), 20)
    return level_priority >= config_priority


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Convert hex color to RGB tuple."""
    hex_color = hex_color.lstrip("#")
    r = int(hex_color[0:2], 16)
    g = int(hex_color[2:4], 16)
    b = int(hex_color[4:6], 16)
    return (r, g, b)


def _get_timestamp() -> str:
    """Get formatted timestamp based on configured timezone."""
    if LOG_TIMEZONE == "UTC":
        now = datetime.now(timezone.utc)
    else:
        now = datetime.now()
    return now.strftime(LOG_TIMESTAMP_FORMAT)


def _format_message(level: str, message: str) -> str:
    """Format log message according to LOG_FORMAT."""
    timestamp = _get_timestamp()
    # Replace Python logging format placeholders
    formatted = LOG_FORMAT
    formatted = formatted.replace("%(asctime)s", timestamp)
    formatted = formatted.replace("%(levelname)s", level)
    formatted = formatted.replace("%(message)s", message)
    return formatted


def _open_file_handler() -> BaseRotatingHandler:
    """Open LOG_FILE with the configured rotation policy."""
    assert LOG_FILE is not None
    # Ensure log directory exists
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)

    if LOG_ROTATION_TYPE == "size":
        return RotatingFileHandler(
            LOG_FILE,
            maxBytes=LOG_ROTATION_SIZE_MB * 1024 * 1024,
            backupCount=LOG_ROTATION_BACKUP_COUNT,
        )
    # "days"
    return TimedRotatingFileHandler(
        LOG_FILE,
        when="D",
        interval=LOG_ROTATION_DAYS,
        backupCount=LOG_ROTATION_BACKUP_COUNT,
    )


def _get_file_handler(ctx: click.Context | None) -> BaseRotatingHandler | None:
    """Get the file handler of an invocation, opening it on first use.

    The handler is kept in the invocation's state and closed with its root
    context, so a caller running the CLI in-process never inherits an open
    file from a previous invocation. Without a context, a new handler is
    opened for the caller to close.

    Args:
        ctx: The context of the running invocation, None outside one

    Returns:
        The handler, or None when file logging is disabled
    """
    if LOG_FILE is None:
        return None
    if ctx is None:
        return _open_file_handler()

    current = state(ctx)
    handler = current.get("log_file_handler")
    if handler is None:
        handler = _open_file_handler()
        current["log_file_handler"] = handler
        ctx.find_root().call_on_close(handler.close)
    return handler


def _log_to_file(formatted_message: str) -> None:
    """Write log message to file if file logging is enabled."""
    ctx = click.get_current_context(silent=True)
    handler = _get_file_handler(ctx)
    if handler is None:
        return

    # Emit through the handler so the configured rotation policy applies.
    handler.emit(makeLogRecord({"msg": formatted_message}))
    if ctx is None:
        # Nothing outlives this call to close it later
        handler.close()


def log(
    level: Literal["DEBUG", "INFO", "WARNING", "ERROR"],
    message: str,
) -> None:
    """Log a message with the appropriate color based on level and style."""
    if not _should_log(level):
        return

    color = LOG_COLORS.get(level, LOG_COLORS["INFO"])
    rgb = hex_to_rgb(color) if colors_enabled() else None
    formatted = _format_message(level, message)

    # Log to console with colors
    if LOG_COLOR_STYLE == "full":
        click.secho(formatted, fg=rgb, err=True)
    else:  # "level" style
        # Find level in formatted string and color only that part
        level_start = formatted.find(level)
        if level_start >= 0:
            level_end = level_start + len(level)
            before = formatted[:level_start]
            after = formatted[level_end:]
            click.echo(before, nl=False, err=True)
            click.secho(level, fg=rgb, nl=False, err=True)
            click.echo(after, err=True)
        else:
            # Fallback if level not found in format
            click.echo(formatted, err=True)

    # Log to file (without colors)
    _log_to_file(formatted)


def log_debug(message: str) -> None:
    """Log a DEBUG message."""
    log("DEBUG", message)


def log_info(message: str) -> None:
    """Log an INFO message."""
    log("INFO", message)


def log_warning(message: str) -> None:
    """Log a WARNING message."""
    log("WARNING", message)


def log_error(message: str) -> None:
    """Log an ERROR message."""
    log("ERROR", message)
