# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""The options every command takes, and the invocation state they start.

``@common_options`` adds them to a group or a command. Their values are not
passed to the decorated function: each option stores what it was given in
``ctx.obj``, the mapping every nested Click context shares, so an option
written after the executable or after a group name applies to the command,
and the command's own value wins when both are given.

That mapping is the whole state of an invocation, and nothing of it lives in
a module global. ``state()`` reads it. Besides the common options under their
parameter names, it holds what the commands derive from them:

- ``settings``: the profile ``load_profile()`` read, as a mapping
- ``log_level`` and ``colors``: the resolved ``logLevel`` and ``outputColors``
  settings, pushed there for the logging module
- ``logger``: the logger of the invocation, its handlers closed with it
"""

from collections.abc import Callable
from pathlib import Path
from typing import Any, TypeVar

import click
from click.core import ParameterSource

from my_cli.constants import OUTPUT_FORMATS

F = TypeVar("F", bound=Callable[..., Any])


def state(ctx: click.Context | None = None) -> dict[str, Any]:
    """Get the state of the running invocation, ``ctx.obj``.

    Args:
        ctx: The context to read, the current one when not given

    Returns:
        The mapping the invocation keeps its state in, or an empty one that
        nothing keeps outside an invocation, so a read there gets the
        generated defaults and an invocation starts clean
    """
    if ctx is None:
        ctx = click.get_current_context(silent=True)
    if ctx is None:
        return {}
    return ctx.ensure_object(dict)


class HeaderType(click.ParamType):
    """A request header given as ``Name: value``."""

    name = "header"

    def convert(
        self, value: Any, param: click.Parameter | None, ctx: click.Context | None
    ) -> tuple[str, str]:
        """Split the header on its first colon, trimming both parts."""
        if isinstance(value, tuple):
            return value
        name, sep, text = str(value).partition(":")
        if not sep or not name.strip():
            self.fail(f"Expected 'Name: value', got '{value}'.", param, ctx)
        return name.strip(), text.strip()


HEADER = HeaderType()


def _remember(ctx: click.Context, param: click.Parameter, value: Any) -> Any:
    """Store an option's value in ctx.obj, unless an outer level set it and
    this one was not given it."""
    ctx.ensure_object(dict)
    name = param.name or ""
    given = ctx.get_parameter_source(name) is not ParameterSource.DEFAULT
    if given or name not in ctx.obj:
        ctx.obj[name] = value
    return value


def _option(*args: str, **kwargs: Any) -> Callable[[F], F]:
    """A click.option that reports to ctx.obj instead of the function."""
    return click.option(*args, expose_value=False, callback=_remember, **kwargs)


# In the order --help lists them
_COMMON_OPTIONS = (
    _option("--profile", "-p", default="default", help="Profile name to use."),
    _option("--debug", "-d", is_flag=True, help="Enable debug output."),
    _option("--base-url", "-u", help="API base URL."),
    _option(
        "--no-verify-ssl",
        is_flag=True,
        default=False,
        help="Disable SSL certificate verification.",
    ),
    _option(
        "--ca-file",
        type=click.Path(exists=True, dir_okay=False, path_type=Path),
        help="CA certificate file for SSL verification.",
    ),
    _option(
        "--timeout",
        type=int,
        help="Seconds to wait for a response, overriding the timeout setting.",
    ),
    _option(
        "--header",
        "-H",
        type=HEADER,
        multiple=True,
        help="Extra request header as 'Name: value'. Repeatable.",
    ),
    _option(
        "--output",
        "-o",
        type=click.Choice(OUTPUT_FORMATS),
        help="Output format, overriding the outputFormat setting.",
    ),
)


def common_options[F: Callable[..., Any]](command: F) -> F:
    """Add the options every command takes; read their values from ctx.obj."""
    # Decorators apply bottom-up and Click lists them top-down, so the last
    # option is applied first to keep the declared order in --help.
    for option in reversed(_COMMON_OPTIONS):
        command = option(command)
    return command
