# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""Rendering of command output in the formats the CLI supports."""

import json
from typing import Any

import yaml

# Border pieces of each table style: the rule drawn above the header, between
# the header and the rows, and below the rows, each as (left, fill, joint,
# right), plus the separator placed between cells. A None rule is not drawn.
Rule = tuple[str, str, str, str] | None

_TABLE_STYLES: dict[str, dict[str, Any]] = {
    "ascii": {
        "top": ("+-", "-", "-+-", "-+"),
        "header": ("+-", "-", "-+-", "-+"),
        "bottom": ("+-", "-", "-+-", "-+"),
        "row": ("| ", " | ", " |"),
    },
    "rounded": {
        "top": ("╭─", "─", "─┬─", "─╮"),
        "header": ("├─", "─", "─┼─", "─┤"),
        "bottom": ("╰─", "─", "─┴─", "─╯"),
        "row": ("│ ", " │ ", " │"),
    },
    "minimal": {
        "top": None,
        "header": ("", "-", "  ", ""),
        "bottom": None,
        "row": ("", "  ", ""),
    },
    "markdown": {
        "top": None,
        "header": ("|-", "-", "-|-", "-|"),
        "bottom": None,
        "row": ("| ", " | ", " |"),
    },
}

# The key/value table a single object is rendered as
_KEY_VALUE_COLUMNS = ["key", "value"]
# The single column a list of scalars is rendered as
_VALUE_COLUMN = ["value"]


def render(
    data: Any,
    output_format: str,
    *,
    json_indent: int = 2,
    table_style: str = "rounded",
) -> str:
    """Render a decoded response in the given format.

    Args:
        data: The decoded JSON of the response
        output_format: "json", "yaml" or "table"
        json_indent: Indentation of the JSON output
        table_style: Borders of the table output, a key of the known styles

    Returns:
        The rendered text, without a trailing newline

    Raises:
        ValueError: if the format or the table style is unknown
    """
    if output_format == "json":
        return json.dumps(data, indent=json_indent)
    if output_format == "yaml":
        return yaml.safe_dump(data, sort_keys=False, allow_unicode=True).rstrip("\n")
    if output_format == "table":
        return render_table(data, table_style)
    raise ValueError(f"Unknown output format: {output_format}")


def render_table(data: Any, style: str = "rounded") -> str:
    """Render a decoded response as a table.

    A list of objects becomes one row per object, with a column for every key
    any of them has, in first-seen order. A single object becomes a key/value
    table and a list of scalars a single-column one. A nested value is shown
    as compact JSON in its cell, so nothing the response holds is dropped.

    Args:
        data: The decoded JSON of the response
        style: Borders of the table, a key of the known styles

    Returns:
        The rendered table, without a trailing newline
    """
    if style not in _TABLE_STYLES:
        raise ValueError(f"Unknown table style: {style}")

    columns, rows = _tabulate(data)
    if not columns:
        return ""
    return _draw(columns, rows, _TABLE_STYLES[style])


def _tabulate(data: Any) -> tuple[list[str], list[list[str]]]:
    """Choose the columns and rows that show the data without losing any of it."""
    if isinstance(data, dict):
        return _KEY_VALUE_COLUMNS, [[str(k), _cell(v)] for k, v in data.items()]
    if isinstance(data, list):
        if not data:
            return [], []
        if all(isinstance(item, dict) for item in data):
            columns: dict[str, None] = {}
            for item in data:
                columns.update(dict.fromkeys(str(k) for k in item))
            rows = [[_cell(item.get(c)) for c in columns] for item in data]
            return list(columns), rows
        return _VALUE_COLUMN, [[_cell(item)] for item in data]
    return _VALUE_COLUMN, [[_cell(data)]]


def _cell(value: Any) -> str:
    """Render one value for a table cell, on a single line."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False)
    return str(value).replace("\n", " ")


def _draw(columns: list[str], rows: list[list[str]], style: dict[str, Any]) -> str:
    """Lay out header and rows in equal-width columns with the style's borders."""
    widths = [
        max(len(column), *(len(row[i]) for row in rows))
        for i, column in enumerate(columns)
    ]
    left, between, right = style["row"]
    lines: list[str] = []

    def rule(spec: Rule) -> None:
        if spec is not None:
            lead, fill, joint, end = spec
            lines.append(lead + joint.join(fill * w for w in widths) + end)

    def row(cells: list[str]) -> None:
        padded = [cell.ljust(w) for cell, w in zip(cells, widths)]
        lines.append((left + between.join(padded) + right).rstrip())

    rule(style["top"])
    row(columns)
    rule(style["header"])
    for cells in rows:
        row(cells)
    rule(style["bottom"])
    return "\n".join(lines)
