# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""Profile management for the generated CLI."""

import os
import re
from typing import Any

import click
import yaml

from my_cli.constants import (
    ENV_PREFIX,
    PROFILE_CHOICES,
    PROFILE_DEFAULTS,
    PROFILE_FILE,
)
from my_cli.errors import ConfigError
from my_cli.log import log_debug, log_error, log_info, log_warning
from my_cli.state import state

# Splits a camelCase profile key before every capital, so "retryMaxAttempts"
# becomes RETRY_MAX_ATTEMPTS once upper-cased.
_CAMEL_BOUNDARY = re.compile(r"(?<!^)(?=[A-Z])")

_TRUTHY = frozenset({"1", "true", "yes", "on"})
_FALSY = frozenset({"0", "false", "no", "off"})


def env_var_name(key: str) -> str:
    """Get the environment variable that overrides a profile key.

    Args:
        key: The profile key, in camelCase

    Returns:
        The environment variable name, e.g. "baseUrl" -> ENV_PREFIX + "BASE_URL"
    """
    return ENV_PREFIX + _CAMEL_BOUNDARY.sub("_", key).upper()


def _coerce(key: str, value: Any, default: Any) -> Any:
    """Convert a value to the type of the built-in default.

    Environment variables always arrive as strings and the profile file is
    hand-editable, so neither layer can be trusted to hold the type the setting
    is used at.

    Args:
        key: The profile key the value belongs to, for error reporting
        value: The value read from the environment or the profile
        default: The built-in default, whose type the value must match

    Returns:
        The converted value, or the built-in default if it cannot be converted
    """
    if default is None:
        return value

    text = str(value).strip()
    try:
        choices = PROFILE_CHOICES.get(key)
        if choices is not None:
            if text in choices:
                return text
            raise ValueError(f"'{value}' is not one of {', '.join(choices)}")
        if isinstance(default, str):
            return value if isinstance(value, str) else str(value)
        # bool is a subclass of int, so it has to be tested first.
        if isinstance(default, bool):
            if text.lower() in _TRUTHY:
                return True
            if text.lower() in _FALSY:
                return False
            raise ValueError(f"'{value}' is not a boolean")
        if isinstance(default, int):
            return int(text)
        if isinstance(default, float):
            return float(text)
    except ValueError as e:
        log_warning(f"Ignoring the value of '{key}': {e}. Falling back to '{default}'.")
        return default
    return value


def _settings() -> dict[str, Any]:
    """Get the profile loaded by the running invocation, empty outside one."""
    settings: dict[str, Any] = state().get("settings", {})
    return settings


def resolve_setting(
    key: str,
    flag_value: Any = None,
    *,
    settings: dict[str, Any] | None = None,
) -> Any:
    """Resolve a setting through the precedence chain.

    The chain is command-line flag > environment variable > profile value >
    built-in default, and every key in PROFILE_DEFAULTS goes through it.

    Args:
        key: The profile key to resolve
        flag_value: The value given on the command line, None when not given
        settings: The profile to resolve against, the one the running
            invocation loaded when not given

    Returns:
        The value of the highest-precedence layer that supplies one
    """
    if flag_value is not None:
        return flag_value

    default = PROFILE_DEFAULTS.get(key)

    raw = os.environ.get(env_var_name(key))
    if raw is not None:
        return _coerce(key, raw, default)

    if settings is None:
        settings = _settings()
    if key in settings:
        return _coerce(key, settings[key], default)

    return default


def load_profile(ctx: click.Context) -> dict[str, Any]:
    """Load the profile the --profile option names into the invocation's state.

    The log level, the colour setting and the JSON indentation are resolved
    here and stored with it: the logging and errors modules cannot resolve them
    themselves without importing this module, which imports them.

    Args:
        ctx: The context of the running invocation

    Returns:
        Profile settings as a dictionary, empty if the file cannot be read

    Raises:
        ConfigError: if the profiles file holds no profile by that name
    """
    current = state(ctx)
    settings = _read_profile(current.get("profile", "default"))

    current["settings"] = settings
    current["log_level"] = str(resolve_setting("logLevel", settings=settings))
    current["colors"] = bool(resolve_setting("outputColors", settings=settings))
    current["json_indent"] = int(resolve_setting("jsonIndent", settings=settings))

    return settings


def profile_file_exists() -> bool:
    """Tell whether the profiles file exists.

    Path.exists() raises on Python before 3.14 when the file's directory cannot
    be searched, and from 3.14 hides that as a missing file, so ask os.stat()
    and tell the two apart on every version.

    Raises:
        ConfigError: if the file's directory cannot be searched, after logging
            it
    """
    try:
        PROFILE_FILE.stat()
    except (FileNotFoundError, NotADirectoryError):
        return False
    except OSError as e:
        message = f"Failed to access profile file: {e}"
        log_error(message)
        raise ConfigError(message) from e
    return True


def read_profiles() -> dict[str, Any]:
    """Read every profile from the profiles file, none when there is no file.

    Raises:
        ConfigError: if the file cannot be read or is not valid YAML, after
            logging it
    """
    if not profile_file_exists():
        return {}
    try:
        with open(PROFILE_FILE) as f:
            profiles: dict[str, Any] = yaml.safe_load(f) or {}
    except (yaml.YAMLError, OSError) as e:
        message = f"Failed to load profile file: {e}"
        log_error(message)
        raise ConfigError(message) from e
    return profiles


def write_profiles(profiles: dict[str, Any]) -> None:
    """Write every profile to the profiles file, readable by its owner alone.

    The directory is created 0700 and the file 0600, and a file left loose by
    an older version is tightened: the file may hold an access token.

    Raises:
        ConfigError: if the file cannot be written, after logging it
    """
    try:
        PROFILE_FILE.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        PROFILE_FILE.touch(mode=0o600, exist_ok=True)
        PROFILE_FILE.chmod(0o600)
        with open(PROFILE_FILE, "w") as f:
            yaml.safe_dump(profiles, f, default_flow_style=False)
    except OSError as e:
        message = f"Failed to save profile file: {e}"
        log_error(message)
        raise ConfigError(message) from e


def _read_profile(profile_name: str) -> dict[str, Any]:
    """Read one profile from the profiles file, the defaults if that fails.

    Raises:
        ConfigError: if the file holds no profile by that name, after logging
            it: a mistyped name must not send the request to another API
    """
    try:
        exists = profile_file_exists()
        profiles: dict[str, Any] = read_profiles() if exists else {"default": {}}
    except ConfigError:
        # Logged already; a command still runs, on the built-in defaults
        return {}
    if not exists:
        log_warning(f"Profile file not found: {PROFILE_FILE}. Creating default.")
        _create_default_profile_file()

    if profile_name not in profiles:
        available = ", ".join(sorted(profiles)) or "none"
        message = (
            f"Profile '{profile_name}' not found in {PROFILE_FILE}."
            f" Available profiles: {available}"
        )
        log_error(message)
        raise ConfigError(message)

    log_debug(f"Loaded profile '{profile_name}'")
    return profiles[profile_name] or {}


def _create_default_profile_file() -> None:
    """Create a default profile file with empty settings."""
    try:
        write_profiles({"default": {}})
    except ConfigError:
        # Logged already; the defaults apply until the file can be written
        return
    log_info(f"Created default profile file: {PROFILE_FILE}")


def get_profile_value(key: str, default: Any = None) -> Any:
    """Get a value from the loaded profile, ignoring flags and the environment.

    Use resolve_setting() to apply the full precedence chain; this reads the
    profile alone.

    Args:
        key: The key to look up
        default: Default value if key not found

    Returns:
        The value from the profile, the profile default,
        or the provided default if not found
    """
    settings = _settings()
    if key in settings:
        return settings[key]
    return PROFILE_DEFAULTS.get(key, default)
