# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""Tests for the main CLI module."""

from click.testing import CliRunner

from my_cli.cli import main


def test_main_help():
    """Test main command help."""
    runner = CliRunner()
    result = runner.invoke(main, ["--help"])
    assert result.exit_code == 0
    assert "CLI Wizard" in result.output


def test_version():
    """Test version option."""
    runner = CliRunner()
    result = runner.invoke(main, ["--version"])
    assert result.exit_code == 0
