# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""Tests for the CLI."""

import importlib
import importlib.metadata
import json
import os
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from click.testing import CliRunner

from my_cli import constants
from my_cli.cli import _hex_to_rgb, _show_splash, main
from my_cli.client import ApiClient, encode_path_param
from my_cli.logging import (
    _format_message,
    _get_file_handler,
    _get_timestamp,
    _log_to_file,
    _should_log,
    is_debug_enabled,
    log,
    log_debug,
    log_error,
    log_info,
    log_warning,
    set_debug,
)
from my_cli.logging import (
    _hex_to_rgb as logging_hex_to_rgb,
)
from my_cli.profile import (
    _create_default_profile_file,
    get_profile,
    get_profile_name,
    get_profile_value,
    load_profile,
)
from my_cli.redaction import REDACTED, redact, redact_text

# =============================================================================
# CLI Tests
# =============================================================================


class TestCli:
    """Tests for main CLI."""

    def test_main_help(self):
        """Test main command help."""
        runner = CliRunner()
        result = runner.invoke(main, ["--help"])
        assert result.exit_code == 0
        assert "A CLI application" in result.output

    def test_version(self):
        """Test version option."""
        runner = CliRunner()
        result = runner.invoke(main, ["--version"])
        assert result.exit_code == 0

    def test_main_no_subcommand(self):
        """Test main without subcommand shows help."""
        runner = CliRunner()
        with patch("my_cli.cli.load_profile"):
            result = runner.invoke(main, [])
        assert result.exit_code == 0
        assert "Usage:" in result.output

    def test_main_with_debug_flag(self):
        """Test main with debug flag."""
        runner = CliRunner()
        result = runner.invoke(main, ["--debug", "--help"])
        assert result.exit_code == 0

    def test_main_with_profile_option(self):
        """Test main with profile option."""
        runner = CliRunner()
        result = runner.invoke(main, ["--profile", "test", "--help"])
        assert result.exit_code == 0

    def test_hex_to_rgb(self):
        """Test hex color to RGB conversion."""
        assert _hex_to_rgb("#FFFFFF") == (255, 255, 255)
        assert _hex_to_rgb("#000000") == (0, 0, 0)
        assert _hex_to_rgb("#FF0000") == (255, 0, 0)
        assert _hex_to_rgb("00FF00") == (0, 255, 0)

    def test_show_splash_disabled(self):
        """Test splash screen when disabled."""
        with patch.object(constants, "SPLASH_ENABLED", False):
            _show_splash()

    def test_show_splash_enabled(self):
        """Test splash screen when enabled."""
        with patch.object(constants, "SPLASH_ENABLED", True):
            with patch("click.echo"):
                with patch("click.secho"):
                    _show_splash()

    def test_show_splash_with_color(self):
        """Test splash screen with color."""
        with tempfile.TemporaryDirectory() as tmpdir:
            splash_file = Path(tmpdir) / "splash.txt"
            splash_file.write_text("Test Splash")
            with patch.object(constants, "SPLASH_ENABLED", True):
                with patch.object(constants, "SPLASH_FILE", splash_file):
                    with patch.object(constants, "SPLASH_COLOR", "#FF0000"):
                        with patch("my_cli.cli.SPLASH_ENABLED", True):
                            with patch(
                                "my_cli.cli.SPLASH_FILE",
                                splash_file,
                            ):
                                with patch(
                                    "my_cli.cli.SPLASH_COLOR",
                                    "#FF0000",
                                ):
                                    with patch("click.secho"):
                                        _show_splash()

    def test_show_splash_without_color(self):
        """Test splash screen without color."""
        with tempfile.TemporaryDirectory() as tmpdir:
            splash_file = Path(tmpdir) / "splash.txt"
            splash_file.write_text("Test Splash")
            with patch.object(constants, "SPLASH_ENABLED", True):
                with patch.object(constants, "SPLASH_FILE", splash_file):
                    with patch.object(constants, "SPLASH_COLOR", None):
                        with patch("my_cli.cli.SPLASH_ENABLED", True):
                            with patch(
                                "my_cli.cli.SPLASH_FILE",
                                splash_file,
                            ):
                                with patch(
                                    "my_cli.cli.SPLASH_COLOR",
                                    None,
                                ):
                                    with patch("click.echo"):
                                        _show_splash()

    def test_main_entry_point(self):
        """Test main entry point."""
        runner = CliRunner()
        result = runner.invoke(main, ["--help"])
        assert result.exit_code == 0


# =============================================================================
# Config Command Tests
# =============================================================================


class TestConfigCommands:
    """Tests for config commands."""

    def test_config_help(self):
        """Test config command help."""
        runner = CliRunner()
        result = runner.invoke(main, ["config", "--help"])
        assert result.exit_code == 0
        assert "Configure the CLI" in result.output

    def test_config_init_creates_file(self):
        """Test config init creates profile file."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            profile_path = Path.cwd() / "profiles.yaml"
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                result = runner.invoke(main, ["config", "init"])
            assert result.exit_code == 0
            json_start = result.output.find("{")
            output = json.loads(result.output[json_start:])
            assert output["status"] == "created"

    def test_config_init_file_exists(self):
        """Test config init when file already exists."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.commands.config.PROFILE_FILE",
                    profile_path,
                ):
                    with patch("my_cli.cli.load_profile"):
                        result = runner.invoke(main, ["config", "init"])
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output["status"] == "exists"

    def test_config_list_profiles_empty(self):
        """Test listing profiles when file doesn't exist."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "nonexistent.yaml"
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.commands.config.PROFILE_FILE",
                    profile_path,
                ):
                    with patch("my_cli.cli.load_profile"):
                        result = runner.invoke(main, ["config", "list-profiles"])
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output["profiles"] == []

    def test_config_list_profiles(self):
        """Test listing profiles."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default: {}\nproduction: {}")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.commands.config.PROFILE_FILE",
                    profile_path,
                ):
                    with patch("my_cli.cli.load_profile"):
                        result = runner.invoke(main, ["config", "list-profiles"])
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert "default" in output["profiles"]
            assert "production" in output["profiles"]

    def test_config_show(self):
        """Test showing profile config."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default:\n  key: value")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.commands.config.PROFILE_FILE",
                    profile_path,
                ):
                    with patch("my_cli.cli.load_profile"):
                        result = runner.invoke(main, ["config", "show"])
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output["key"] == "value"

    def test_config_show_nonexistent_profile(self):
        """Test showing nonexistent profile."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.commands.config.PROFILE_FILE",
                    profile_path,
                ):
                    with patch("my_cli.cli.load_profile"):
                        result = runner.invoke(
                            main, ["config", "show", "-p", "nonexistent"]
                        )
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output == {}

    def test_config_get(self):
        """Test getting a config value."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default:\n  mykey: myvalue")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.commands.config.PROFILE_FILE",
                    profile_path,
                ):
                    with patch("my_cli.cli.load_profile"):
                        result = runner.invoke(
                            main,
                            ["config", "get", "--param", "mykey"],
                        )
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output["key"] == "mykey"
            assert output["value"] == "myvalue"

    def test_config_get_nonexistent_key(self):
        """Test getting a nonexistent config value."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.commands.config.PROFILE_FILE",
                    profile_path,
                ):
                    with patch("my_cli.cli.load_profile"):
                        result = runner.invoke(
                            main,
                            [
                                "config",
                                "get",
                                "--param",
                                "nonexistent",
                            ],
                        )
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output["value"] is None

    def test_config_set(self):
        """Test setting a config value."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            profile_path = Path.cwd() / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                result = runner.invoke(
                    main,
                    [
                        "config",
                        "set",
                        "--param",
                        "newkey",
                        "--value",
                        "newvalue",
                    ],
                )
            assert result.exit_code == 0
            json_start = result.output.find("{")
            output = json.loads(result.output[json_start:])
            assert output["key"] == "newkey"
            assert output["value"] == "newvalue"

    def test_config_set_json_value(self):
        """Test setting a JSON config value."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            profile_path = Path.cwd() / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                result = runner.invoke(
                    main,
                    [
                        "config",
                        "set",
                        "--param",
                        "list",
                        "--value",
                        '["a", "b"]',
                    ],
                )
            assert result.exit_code == 0
            json_start = result.output.find("{")
            output = json.loads(result.output[json_start:])
            assert output["value"] == ["a", "b"]

    def test_config_unset(self):
        """Test unsetting a config value."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            profile_path = Path.cwd() / "profiles.yaml"
            profile_path.write_text("default:\n  mykey: myvalue")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                result = runner.invoke(
                    main,
                    ["config", "unset", "--param", "mykey"],
                )
            assert result.exit_code == 0
            json_start = result.output.find("{")
            output = json.loads(result.output[json_start:])
            assert output["oldValue"] == "myvalue"

    def test_config_unset_nonexistent_key(self):
        """Test unsetting a nonexistent config value."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            profile_path = Path.cwd() / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                result = runner.invoke(
                    main,
                    [
                        "config",
                        "unset",
                        "--param",
                        "nonexistent",
                    ],
                )
            assert result.exit_code == 0
            json_start = result.output.find("{")
            output = json.loads(result.output[json_start:])
            assert output["oldValue"] is None

    def test_config_unset_file_not_exists(self):
        """Test unsetting when profile file doesn't exist."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "nonexistent.yaml"
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                with patch("my_cli.cli.load_profile"):
                    result = runner.invoke(
                        main,
                        ["config", "unset", "--param", "mykey"],
                    )
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output["oldValue"] is None

    def test_config_unset_nonexistent_profile(self):
        """Test unsetting from nonexistent profile."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                with patch("my_cli.cli.load_profile"):
                    result = runner.invoke(
                        main,
                        [
                            "config",
                            "unset",
                            "--param",
                            "mykey",
                            "-p",
                            "nonexistent",
                        ],
                    )
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output["oldValue"] is None

    def test_config_init_error_handling(self):
        """Test config init error handling."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "readonly" / "profiles.yaml"
            readonly_dir = Path(tmpdir) / "readonly"
            readonly_dir.mkdir()
            os.chmod(readonly_dir, 0o444)
            try:
                with patch(
                    "my_cli.commands.config.PROFILE_FILE",
                    profile_path,
                ):
                    with patch("my_cli.cli.load_profile"):
                        result = runner.invoke(main, ["config", "init"])
                assert result.exit_code in [0, 1]
            finally:
                os.chmod(readonly_dir, 0o755)

    def test_config_list_profiles_yaml_error(self):
        """Test list profiles with invalid YAML."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("invalid: yaml: content: [")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                with patch("my_cli.cli.load_profile"):
                    result = runner.invoke(main, ["config", "list-profiles"])
            assert result.exit_code == 1

    def test_config_show_yaml_error(self):
        """Test show with invalid YAML."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("invalid: yaml: content: [")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                with patch("my_cli.cli.load_profile"):
                    result = runner.invoke(main, ["config", "show"])
            assert result.exit_code == 1

    def test_config_show_file_not_exists(self):
        """Test show when profile file doesn't exist."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "nonexistent.yaml"
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                with patch("my_cli.cli.load_profile"):
                    result = runner.invoke(main, ["config", "show"])
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output == {}

    def test_config_get_yaml_error(self):
        """Test get with invalid YAML."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("invalid: yaml: content: [")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                with patch("my_cli.cli.load_profile"):
                    result = runner.invoke(
                        main,
                        [
                            "config",
                            "get",
                            "--param",
                            "mykey",
                        ],
                    )
            assert result.exit_code == 1

    def test_config_get_file_not_exists(self):
        """Test get when profile file doesn't exist."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "nonexistent.yaml"
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                with patch("my_cli.cli.load_profile"):
                    result = runner.invoke(
                        main,
                        [
                            "config",
                            "get",
                            "--param",
                            "mykey",
                        ],
                    )
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output["value"] is None

    def test_config_get_nonexistent_profile(self):
        """Test get from nonexistent profile."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                with patch("my_cli.cli.load_profile"):
                    result = runner.invoke(
                        main,
                        [
                            "config",
                            "get",
                            "--param",
                            "mykey",
                            "-p",
                            "nonexistent",
                        ],
                    )
            assert result.exit_code == 0
            output = json.loads(result.output)
            assert output["value"] is None

    def test_config_set_yaml_error(self):
        """Test set with invalid YAML."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("invalid: yaml: content: [")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                with patch("my_cli.cli.load_profile"):
                    result = runner.invoke(
                        main,
                        [
                            "config",
                            "set",
                            "--param",
                            "mykey",
                            "--value",
                            "myvalue",
                        ],
                    )
            assert result.exit_code == 1

    def test_config_set_creates_profile(self):
        """Test set creates profile if it doesn't exist."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            profile_path = Path.cwd() / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                result = runner.invoke(
                    main,
                    [
                        "config",
                        "set",
                        "--param",
                        "mykey",
                        "--value",
                        "myvalue",
                        "-p",
                        "newprofile",
                    ],
                )
            assert result.exit_code == 0
            json_start = result.output.find("{")
            output = json.loads(result.output[json_start:])
            assert output["key"] == "mykey"
            assert output["value"] == "myvalue"

    def test_config_set_file_not_exists(self):
        """Test set when profile file doesn't exist."""
        runner = CliRunner()
        with runner.isolated_filesystem():
            profile_path = Path.cwd() / "profiles.yaml"
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                result = runner.invoke(
                    main,
                    [
                        "config",
                        "set",
                        "--param",
                        "mykey",
                        "--value",
                        "myvalue",
                    ],
                )
            assert result.exit_code == 0
            json_start = result.output.find("{")
            output = json.loads(result.output[json_start:])
            assert output["key"] == "mykey"

    def test_config_unset_yaml_error(self):
        """Test unset with invalid YAML."""
        runner = CliRunner()
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("invalid: yaml: content: [")
            with patch(
                "my_cli.commands.config.PROFILE_FILE",
                profile_path,
            ):
                with patch("my_cli.cli.load_profile"):
                    result = runner.invoke(
                        main,
                        [
                            "config",
                            "unset",
                            "--param",
                            "mykey",
                        ],
                    )
            assert result.exit_code == 1


# =============================================================================
# Client Tests
# =============================================================================


class TestApiClient:
    """Tests for API client."""

    def test_client_init_default(self):
        """Test client initialization with defaults."""
        client = ApiClient()
        assert client.base_url == constants.DEFAULT_BASE_URL
        assert client.timeout == constants.DEFAULT_TIMEOUT

    def test_client_init_custom(self):
        """Test client initialization with custom values."""
        client = ApiClient(
            base_url="https://api.example.com/",
            access_token="test-token",
            timeout=60,
            verify_ssl=False,
        )
        assert client.base_url == "https://api.example.com"
        assert client.access_token == "test-token"
        assert client.timeout == 60
        assert client.verify_ssl is False

    def test_client_headers_with_token(self):
        """Test client sets auth header with token."""
        client = ApiClient(access_token="my-token")
        assert client.session.headers["Authorization"] == "Bearer my-token"

    def test_client_headers_without_token(self):
        """Test client without auth header."""
        client = ApiClient()
        assert "Authorization" not in client.session.headers

    def test_client_url_building(self):
        """Test URL building."""
        client = ApiClient(base_url="https://api.example.com")
        assert client._url("/users") == "https://api.example.com/users"

    def test_client_ssl_disabled(self):
        """Test SSL verification disabled."""
        client = ApiClient(verify_ssl=False)
        assert client.session.verify is False

    def test_client_ssl_with_ca_file(self):
        """Test SSL with custom CA file."""
        with tempfile.NamedTemporaryFile(suffix=".pem", delete=False) as f:
            f.write(b"fake cert")
            ca_path = f.name
        try:
            client = ApiClient(ca_file=ca_path)
            assert client.session.verify == ca_path
        finally:
            os.unlink(ca_path)

    @patch("requests.Session.get")
    def test_client_get(self, mock_get):
        """Test GET request."""
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_get.return_value = mock_response

        client = ApiClient(base_url="https://api.example.com")
        response = client.get("/users", params={"page": 1})

        mock_get.assert_called_once()
        assert response.status_code == 200

    @patch("requests.Session.post")
    def test_client_post(self, mock_post):
        """Test POST request."""
        mock_response = MagicMock()
        mock_response.status_code = 201
        mock_post.return_value = mock_response

        client = ApiClient(base_url="https://api.example.com")
        response = client.post("/users", json_data={"name": "test"})

        mock_post.assert_called_once()
        assert response.status_code == 201

    @patch("requests.Session.put")
    def test_client_put(self, mock_put):
        """Test PUT request."""
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_put.return_value = mock_response

        client = ApiClient(base_url="https://api.example.com")
        response = client.put("/users/1", json_data={"name": "updated"})

        mock_put.assert_called_once()
        assert response.status_code == 200

    @patch("requests.Session.patch")
    def test_client_patch(self, mock_patch):
        """Test PATCH request."""
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_patch.return_value = mock_response

        client = ApiClient(base_url="https://api.example.com")
        response = client.patch("/users/1", json_data={"name": "patched"})

        mock_patch.assert_called_once()
        assert response.status_code == 200

    @patch("requests.Session.delete")
    def test_client_delete(self, mock_delete):
        """Test DELETE request."""
        mock_response = MagicMock()
        mock_response.status_code = 204
        mock_delete.return_value = mock_response

        client = ApiClient(base_url="https://api.example.com")
        response = client.delete("/users/1")

        mock_delete.assert_called_once()
        assert response.status_code == 204

    @pytest.mark.parametrize("method", ["post", "put", "patch", "delete"])
    def test_client_sends_query_parameters_without_a_get(self, method):
        """Test query parameters are forwarded by the non-GET methods."""
        client = ApiClient(base_url="https://api.example.com")

        with patch(f"requests.Session.{method}") as mock_send:
            getattr(client, method)("/users/1", params={"force": True})

        assert mock_send.call_args.kwargs["params"] == {"force": True}

    @pytest.mark.parametrize(
        "value,expected",
        [
            ("plain", "plain"),
            ("a@b.com", "a%40b.com"),
            ("with space", "with%20space"),
            ("with/slash", "with%2Fslash"),
            (42, "42"),
        ],
    )
    def test_encode_path_param(self, value, expected):
        """Test a path parameter value is encoded into a single segment."""
        assert encode_path_param(value) == expected

    def test_client_debug_logging(self):
        """Test client debug logging."""
        client = ApiClient(debug=True)
        with patch("my_cli.client.log_debug") as mock_log:
            client._log_request("GET", "https://api.example.com/test")
            mock_log.assert_called()

    def test_client_no_debug_logging(self):
        """Test client without debug logging."""
        client = ApiClient(debug=False)
        with patch("my_cli.client.log_debug") as mock_log:
            client._log_request("GET", "https://api.example.com/test")
            mock_log.assert_not_called()

    def test_client_debug_response_logging(self):
        """Test client debug response logging."""
        client = ApiClient(debug=True)
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.reason = "OK"
        mock_response.headers = {"Content-Type": "application/json"}
        mock_response.text = '{"result": "success"}'
        with patch("my_cli.client.log_debug") as mock_log:
            client._log_response(mock_response)
            assert mock_log.call_count >= 2

    def test_client_no_debug_response_logging(self):
        """Test client without debug response logging."""
        client = ApiClient(debug=False)
        mock_response = MagicMock()
        mock_response.status_code = 200
        with patch("my_cli.client.log_debug") as mock_log:
            client._log_response(mock_response)
            mock_log.assert_not_called()

    def test_client_debug_request_with_params_and_body(self):
        """Test client debug logging with params and body."""
        client = ApiClient(debug=True)
        with patch("my_cli.client.log_debug") as mock_log:
            client._log_request(
                "POST",
                "https://api.example.com/test",
                params={"page": 1},
                json_data={"name": "test"},
            )
            assert mock_log.call_count >= 3

    def test_client_debug_redacts_the_request(self):
        """Test a request credential never reaches debug output."""
        client = ApiClient(debug=True, access_token="eyJTOKEN")
        with patch("my_cli.client.log_debug") as mock_log:
            client._log_request(
                "POST",
                "https://api.example.com/login",
                json_data={"email": "a@b.com", "password": "hunter2"},
            )
        logged = " ".join(str(call) for call in mock_log.call_args_list)
        assert "hunter2" not in logged
        assert "eyJTOKEN" not in logged
        assert "a@b.com" in logged

    def test_client_debug_redacts_the_response(self):
        """Test a response credential never reaches debug output.

        The credential sits past the 1000-character truncation point, so
        this also pins that redaction happens before truncation.
        """
        client = ApiClient(debug=True)
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.reason = "OK"
        mock_response.headers = {"Set-Cookie": "session=abcd"}
        mock_response.text = json.dumps(
            {"padding": "x" * 2000, "access_token": "eyJTOKEN"}
        )
        with patch("my_cli.client.log_debug") as mock_log:
            client._log_response(mock_response)
        logged = " ".join(str(call) for call in mock_log.call_args_list)
        assert "eyJTOKEN" not in logged
        assert "session=abcd" not in logged


# =============================================================================
# Redaction Tests
# =============================================================================


class TestRedaction:
    """Tests for credential redaction in debug output."""

    @pytest.mark.parametrize(
        "name", ["password", "Password", "accessToken", "client_secret", "api_key"]
    )
    def test_redact_replaces_credential_values(self, name):
        """Test credential-looking fields are replaced with the marker."""
        assert redact({name: "value"}) == {name: REDACTED}

    @pytest.mark.parametrize("name", ["email", "name", "limit", "id"])
    def test_redact_keeps_ordinary_values(self, name):
        """Test ordinary fields are left readable."""
        assert redact({name: "value"}) == {name: "value"}

    def test_redact_walks_nested_structures(self):
        """Test credentials nested in sub-objects are redacted."""
        result = redact({"users": [{"name": "a", "token": "t"}]})
        assert result == {"users": [{"name": "a", "token": REDACTED}]}

    def test_redact_leaves_the_payload_untouched(self):
        """Test redaction does not mutate its input."""
        payload = {"password": "hunter2"}
        redact(payload)
        assert payload == {"password": "hunter2"}

    @pytest.mark.parametrize(
        "header", ["Authorization", "Cookie", "Set-Cookie", "X-Api-Key"]
    )
    def test_redact_masks_credential_headers(self, header):
        """Test headers carrying a credential are masked."""
        assert redact({header: "Bearer eyJ"}) == {header: REDACTED}

    def test_redact_text_redacts_json_payloads(self):
        """Test JSON payloads are redacted structurally."""
        result = redact_text('{"access_token": "eyJ", "id": 7}')
        assert json.loads(result) == {"access_token": REDACTED, "id": 7}

    def test_redact_text_redacts_non_json_payloads(self):
        """Test form-encoded payloads are redacted by pattern."""
        result = redact_text("access_token=eyJ&expires_in=3600")
        assert "eyJ" not in result
        assert "expires_in=3600" in result

    def test_redact_text_leaves_ordinary_text_intact(self):
        """Test text without credentials passes through unchanged."""
        assert redact_text("<html>Not Found</html>") == "<html>Not Found</html>"


# =============================================================================
# Profile Tests
# =============================================================================


class TestProfile:
    """Tests for profile management."""

    def test_load_profile_file_not_exists(self):
        """Test loading profile when file doesn't exist."""
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "nonexistent" / "profiles.yaml"
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.profile.PROFILE_FILE",
                    profile_path,
                ):
                    result = load_profile("default")
            assert result == {}

    def test_load_profile_success(self):
        """Test loading profile successfully."""
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default:\n  key: value")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.profile.PROFILE_FILE",
                    profile_path,
                ):
                    result = load_profile("default")
            assert result == {"key": "value"}

    def test_load_profile_not_found(self):
        """Test loading nonexistent profile."""
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.profile.PROFILE_FILE",
                    profile_path,
                ):
                    result = load_profile("nonexistent")
            assert result == {}

    def test_get_profile(self):
        """Test getting current profile."""
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default:\n  key: value")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.profile.PROFILE_FILE",
                    profile_path,
                ):
                    load_profile("default")
                    result = get_profile()
            assert result == {"key": "value"}

    def test_get_profile_name(self):
        """Test getting current profile name."""
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("myprofile: {}")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.profile.PROFILE_FILE",
                    profile_path,
                ):
                    load_profile("myprofile")
                    result = get_profile_name()
            assert result == "myprofile"

    def test_get_profile_value(self):
        """Test getting profile value."""
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default:\n  mykey: myvalue")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.profile.PROFILE_FILE",
                    profile_path,
                ):
                    load_profile("default")
                    result = get_profile_value("mykey")
            assert result == "myvalue"

    def test_get_profile_value_default(self):
        """Test getting profile value with default."""
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("default: {}")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.profile.PROFILE_FILE",
                    profile_path,
                ):
                    load_profile("default")
                    result = get_profile_value("nonexistent", "default_value")
            assert result == "default_value"

    def test_load_profile_yaml_error(self):
        """Test loading profile with invalid YAML."""
        with tempfile.TemporaryDirectory() as tmpdir:
            profile_path = Path(tmpdir) / "profiles.yaml"
            profile_path.write_text("invalid: yaml: content: [")
            with patch.object(constants, "PROFILE_FILE", profile_path):
                with patch(
                    "my_cli.profile.PROFILE_FILE",
                    profile_path,
                ):
                    result = load_profile("default")
            assert result == {}

    def test_create_default_profile_file_error(self):
        """Test creating default profile file with error."""
        with tempfile.TemporaryDirectory() as tmpdir:
            readonly_dir = Path(tmpdir) / "readonly"
            readonly_dir.mkdir()
            profile_path = readonly_dir / "subdir" / "profiles.yaml"
            os.chmod(readonly_dir, 0o444)
            try:
                with patch.object(constants, "PROFILE_FILE", profile_path):
                    with patch(
                        "my_cli.profile.PROFILE_FILE",
                        profile_path,
                    ):
                        _create_default_profile_file()
            finally:
                os.chmod(readonly_dir, 0o755)


# =============================================================================
# Logging Tests
# =============================================================================


class TestLogging:
    """Tests for logging utilities."""

    def test_set_debug(self):
        """Test setting debug mode."""
        set_debug(True)
        assert is_debug_enabled() is True
        set_debug(False)
        assert is_debug_enabled() is False

    def test_should_log_debug_enabled(self):
        """Test log filtering with debug enabled."""
        set_debug(True)
        assert _should_log("DEBUG") is True
        assert _should_log("INFO") is True
        set_debug(False)

    def test_should_log_by_level(self):
        """Test log filtering by level."""
        set_debug(False)
        with patch.object(constants, "LOG_LEVEL", "WARNING"):
            pass

    def test_hex_to_rgb_logging(self):
        """Test hex to RGB conversion in logging."""
        assert logging_hex_to_rgb("#FF0000") == (255, 0, 0)
        assert logging_hex_to_rgb("#00FF00") == (0, 255, 0)
        assert logging_hex_to_rgb("#0000FF") == (0, 0, 255)

    def test_get_timestamp(self):
        """Test timestamp generation."""
        timestamp = _get_timestamp()
        assert isinstance(timestamp, str)
        assert len(timestamp) > 0

    def test_format_message(self):
        """Test message formatting."""
        formatted = _format_message("INFO", "Test message")
        assert "INFO" in formatted
        assert "Test message" in formatted

    def test_log_debug(self):
        """Test debug logging."""
        set_debug(True)
        with patch("click.echo"):
            with patch("click.secho"):
                log_debug("Debug message")
        set_debug(False)

    def test_log_info(self):
        """Test info logging."""
        set_debug(True)
        with patch("click.echo"):
            with patch("click.secho"):
                log_info("Info message")
        set_debug(False)

    def test_log_warning(self):
        """Test warning logging."""
        set_debug(True)
        with patch("click.echo"):
            with patch("click.secho"):
                log_warning("Warning message")
        set_debug(False)

    def test_log_error(self):
        """Test error logging."""
        set_debug(True)
        with patch("click.echo"):
            with patch("click.secho"):
                log_error("Error message")
        set_debug(False)

    def test_log_full_color_style(self):
        """Test logging with full color style."""
        set_debug(True)
        with patch.object(constants, "LOG_COLOR_STYLE", "full"):
            with patch("click.secho"):
                with patch(
                    "my_cli.logging.LOG_COLOR_STYLE",
                    "full",
                ):
                    log("INFO", "Test message")
        set_debug(False)

    def test_log_level_color_style(self):
        """Test logging with level color style."""
        set_debug(True)
        with patch.object(constants, "LOG_COLOR_STYLE", "level"):
            with patch(
                "my_cli.logging.LOG_COLOR_STYLE",
                "level",
            ):
                with patch("click.echo"):
                    with patch("click.secho"):
                        log("INFO", "Test message")
        set_debug(False)

    def test_log_to_file(self):
        """Test logging to file."""
        set_debug(True)
        with tempfile.TemporaryDirectory() as tmpdir:
            log_file = Path(tmpdir) / "test.log"
            with patch("my_cli.logging.LOG_FILE", log_file):
                with patch(
                    "my_cli.logging._file_handler",
                    None,
                ):
                    with patch("click.echo"):
                        with patch("click.secho"):
                            log_info("Test file logging")
        set_debug(False)

    def test_get_file_handler_size_rotation(self):
        """Test file handler with size rotation."""
        with tempfile.TemporaryDirectory() as tmpdir:
            log_file = Path(tmpdir) / "test.log"
            with patch("my_cli.logging.LOG_FILE", log_file):
                with patch(
                    "my_cli.logging.LOG_ROTATION_TYPE",
                    "size",
                ):
                    with patch(
                        "my_cli.logging._file_handler",
                        None,
                    ):
                        _get_file_handler()

    def test_get_file_handler_days_rotation(self):
        """Test file handler with days rotation."""
        with tempfile.TemporaryDirectory() as tmpdir:
            log_file = Path(tmpdir) / "test.log"
            with patch("my_cli.logging.LOG_FILE", log_file):
                with patch(
                    "my_cli.logging.LOG_ROTATION_TYPE",
                    "days",
                ):
                    with patch(
                        "my_cli.logging._file_handler",
                        None,
                    ):
                        _get_file_handler()

    def test_get_file_handler_none(self):
        """Test file handler when LOG_FILE is None."""
        with patch("my_cli.logging.LOG_FILE", None):
            with patch("my_cli.logging._file_handler", None):
                handler = _get_file_handler()
                assert handler is None

    def test_log_to_file_io_error(self):
        """Test logging to file handles IO errors gracefully."""
        with tempfile.TemporaryDirectory() as tmpdir:
            log_file = Path(tmpdir) / "readonly" / "test.log"
            with patch("my_cli.logging.LOG_FILE", log_file):
                mock_handler = MagicMock()
                with patch(
                    "my_cli.logging._get_file_handler",
                    return_value=mock_handler,
                ):
                    _log_to_file("Test message")


# =============================================================================
# Constants Tests
# =============================================================================


class TestConstants:
    """Tests for constants module."""

    def test_version_exists(self):
        """Test version constant exists."""
        assert hasattr(constants, "__version__")
        assert isinstance(constants.__version__, str)

    def test_version_fallback_when_package_not_found(self, monkeypatch):
        """Test version falls back to '0.0.0' when metadata is unavailable."""

        def fake_version(name):
            raise importlib.metadata.PackageNotFoundError(name)

        monkeypatch.setattr(importlib.metadata, "version", fake_version)
        try:
            importlib.reload(constants)
            assert constants.__version__ == "0.0.0"
        finally:
            monkeypatch.undo()
            importlib.reload(constants)

    def test_main_dir_exists(self):
        """Test main directory constant exists."""
        assert hasattr(constants, "MAIN_DIR")
        assert isinstance(constants.MAIN_DIR, Path)

    def test_profile_file_exists(self):
        """Test profile file constant exists."""
        assert hasattr(constants, "PROFILE_FILE")
        assert isinstance(constants.PROFILE_FILE, Path)

    def test_default_values(self):
        """Test default value constants."""
        assert hasattr(constants, "DEFAULT_BASE_URL")
        assert hasattr(constants, "DEFAULT_TIMEOUT")
        assert isinstance(constants.DEFAULT_TIMEOUT, int)

    def test_log_colors(self):
        """Test log color constants."""
        assert hasattr(constants, "LOG_COLORS")
        assert "DEBUG" in constants.LOG_COLORS
        assert "INFO" in constants.LOG_COLORS
        assert "WARNING" in constants.LOG_COLORS
        assert "ERROR" in constants.LOG_COLORS
