# Copyright (c) 2026, Firstname Lastname
# Licensed under the MIT License

# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by CLI Wizard https://pypi.org/project/cli-wizard

"""Tests for the commands generated from the API specification."""

from unittest.mock import patch

import pytest
from click.testing import CliRunner

from my_cli.cli import main

BASE_URL = "http://api.test"


@pytest.fixture
def request_mock(tmp_path):
    """Record requests instead of sending them, off the real profile file."""
    with (
        patch("requests.Session.request") as request,
        patch("my_cli.profile.PROFILE_FILE", tmp_path / "profiles.yaml"),
        patch("my_cli.logging.LOG_FILE", None),
    ):
        request.return_value.text = ""
        yield request


def _run(request_mock, args):
    """Run a generated command and return the request it made."""
    result = CliRunner().invoke(main, [*args, "--base-url", BASE_URL])
    assert result.exit_code == 0, result.output
    return request_mock.call_args


class TestPrivateCommands:
    """Tests for the private commands."""

    def test_get_greetings(self, request_mock):
        """Test get-greetings sends the request the spec describes."""
        call = _run(request_mock, ["private", "get-greetings"])
        assert call.args == ("GET", BASE_URL + "/private/greetings")
        assert call.kwargs["params"] is None


class TestPublicCommands:
    """Tests for the public commands."""

    def test_get_public_greetings(self, request_mock):
        """Test get-public-greetings sends the request the spec describes."""
        call = _run(request_mock, ["public", "get-public-greetings"])
        assert call.args == ("GET", BASE_URL + "/public/greetings")
        assert call.kwargs["params"] is None
