[tox]
envlist = py312,py313,py314
isolated_build = True

[testenv]
deps =
    pytest
    pytest-cov
commands =
    pytest tests/ -v --cov=my_cli --cov-report=term

[testenv:lint]
deps =
    mypy
    ruff~=0.16.2
    types-PyYAML
    types-requests
commands =
    ruff check src/ tests/
    ruff format --check src/ tests/
    mypy src/

[testenv:format]
deps = ruff~=0.16.2
commands =
    ruff check --fix src/ tests/
    ruff format src/ tests/
